-- Migration: Create zoom_transcriptions table

CREATE TABLE IF NOT EXISTS `zoom_transcriptions` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `user_id` VARCHAR(255) NOT NULL COMMENT 'User ID who requested the transcription',
    `teacher_id` VARCHAR(255) NOT NULL COMMENT 'Teacher ID associated with the meeting',
    `class_id` VARCHAR(255) NOT NULL COMMENT 'Class ID associated with the meeting',
    `teacher_email` VARCHAR(255) NOT NULL COMMENT 'Teacher email from Zoom',
    `meeting_id` VARCHAR(255) NOT NULL UNIQUE COMMENT 'Zoom meeting ID',
    `meeting_topic` VARCHAR(500) DEFAULT NULL COMMENT 'Zoom meeting topic/title',
    `meeting_date` DATE DEFAULT NULL COMMENT 'Date of the meeting (YYYY-MM-DD)',
    `meeting_time` TIME DEFAULT NULL COMMENT 'Time of the meeting (HH:MM:SS)',
    `time_range` VARCHAR(100) DEFAULT NULL COMMENT 'Time range filter used',
    `audio_file_name` VARCHAR(500) DEFAULT NULL COMMENT 'Downloaded audio file name',
    `audio_file_size_mb` DECIMAL(10, 2) DEFAULT 0 COMMENT 'Audio file size in MB',
    `transcript` LONGTEXT DEFAULT NULL COMMENT 'Full transcription text',
    `transcript_length` INT(11) DEFAULT 0 COMMENT 'Length of transcript in characters',
    `transcript_source` VARCHAR(50) DEFAULT 'assemblyai' COMMENT 'Source of transcription',
    `transcription_status` ENUM('pending', 'processing', 'completed', 'failed') NOT NULL DEFAULT 'pending' COMMENT 'Current status',
    `processing_mode` VARCHAR(100) DEFAULT 'audio_transcription' COMMENT 'Processing mode used',
    `transcription_service` VARCHAR(100) DEFAULT 'AssemblyAI' COMMENT 'AI service used',
    `error_message` TEXT DEFAULT NULL COMMENT 'Error message if failed',
    `processing_started_at` DATETIME DEFAULT NULL COMMENT 'When processing started',
    `processing_completed_at` DATETIME DEFAULT NULL COMMENT 'When processing completed',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_teacher_id` (`teacher_id`),
    INDEX `idx_class_id` (`class_id`),
    INDEX `idx_meeting_date` (`meeting_date`),
    INDEX `idx_transcription_status` (`transcription_status`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Zoom audio transcriptions table';